### ISSUE TITLE
Merge Text.Parser.String into gallais/agdarsec

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/schmitty#8]

**Comment by tuncbkose** [comment]
Hi @wenkokke! While trying to run
```agda
 {-# OPTIONS --allow-exec #-}

open import Data.Integer
open import Data.List
open import Data.Product
open import Relation.Binary.PropositionalEquality
open import SMT.Theories.Ints as Ints
open import SMT.Backend.Z3 Ints.reflectable

verycool : ∀ (x y : ℤ) → x ≤ y → y ≤ x → x ≡ y
verycool = solveZ3
```
I encountered the following error.:
```
Error raised at typeError, called at src/full/Agda/TypeChecking/Monad/State.hs:208:3 in Agda-2.6.2-inplace:Agda.TypeChecking.Monad.State
~/work/schmitty-master/src/Text/Parser/String.agda:35,41-54
The module Parser doesn't export the following:
  _^_,_
when scope checking the declaration
  open import Text.Parser.Types as Parser using (_^_,_)
~/work/schmitty-master/src/Text/Parser/String.agda:53,17-31
Not in scope:
  Parser.Success
  at /home/vagrant/work/schmitty-master/src/Text/Parser/String.agda:53,17-31
    (did you mean 'Success'?)
when scope checking Parser.Success
```
Is this related to this issue? Apologies if this is obvious, I am new to Agda.

**Comment by wenkokke** [comment]
Heya, @tuncbkose! I haven't had the time yet to update Schmitty to work with agdarsec 0.4.1, and I don't think @gallais strictly adheres to semantic versioning. You should be able to get Schmitty to work with version 0.4.0. If you're happy to submit a patch to work with 0.4.1, that would be extremely welcome!

**Comment by gallais** [comment]
I think we're getting there with: https://github.com/gallais/agdarsec/pull/27

**Comment by wenkokke** [comment]
Solved in #30.
